import BlogComponent from '@/Components/BlogComponent/BlogComponent';
import React from 'react'
export const metadata = {
  title: " HEXASHOP - Products",
  description: "Generated by create next app",
};
const page = () => {

  return <>
  <BlogComponent />
  </>
}

export default page