import About from '@/Components/About/About'
import React from 'react'
export const metadata = {
  title: " About",
  description: "Generated by create next app",
};
const page = () => {
  return <>
  <About />
  </>
}

export default page