import { Inter,Lalezar} from "next/font/google";
import "./globals.css";
import Footer from "@/Components/Footer/Footer";
import Navbar from "@/Components/Navbar/Navbar";
import AppWrapper from "@/Context/Context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: " HEXASHOP - Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={`${inter.className} `}>
        <Navbar />
          <AppWrapper>
      {children}

          </AppWrapper>
        
       <Footer /> 
        </body>
    </html>
  );
}
